# Generated by Django 5.1.3 on 2024-11-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bewerbung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('company', models.CharField(max_length=100, verbose_name='Unternehmen')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
                ('date_applied', models.DateField(verbose_name='Bewerbungsdatum')),
                ('status', models.CharField(choices=[('Pending', 'Ausstehend'), ('Interview', 'Interview'), ('Accepted', 'Angenommen'), ('Rejected', 'Abgelehnt')], default='Pending', max_length=50, verbose_name='Status')),
            ],
        ),
    ]
